### ISSUE TITLE
Highlights break and render escape sequences on Unicode symbols

### ISSUE THREAD

**Issue by postsolar** [hadronized/kak-tree-sitter#156]
No KTS:

![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/f93496d3-a6c4-42a6-932e-0968f9530e1b)
![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/db86510d-8bce-40c0-8c41-fbeb24a8b240)

KTS:

![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/63793ce2-4028-4431-b5b9-4b64a07382d9)
![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/11317100-a48e-4228-ac8e-f7e80aa12274)

Sorry if it's not related to kak-tree-sitter, I'm new to this editor.

**Comment by chriselrod** [comment]
I'm getting the same thing.

**Comment by phaazon** [comment]
That’s odd. Which version are you using? `kak-tree-sitter --version`

**Comment by postsolar** [comment]
`0.4.6-` (yes, with the dash at the end)

**Comment by Sivecano** [comment]
I'm having the same issue on version 0.4.6-4592fcf

**Comment by phaazon** [comment]
Yes, I’ve been reproducing too. Thanks for reporting!

**Comment by postsolar** [comment]
It became different.
![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/39e730b6-82e2-4167-a2c6-d41b0a2c72d9)

Now it's these fancy red chars instead of escape sequences. I also noticed that different characters act differently: for example ∧/∨ are simply not displayed at all (they're present on the screenshot at the end of first line and on the last line).

**Comment by postsolar** [comment]
Oh that bit is actually just different terminals acting in different ways. Foot still renders escape sequences, whereas kitty renders these characters. But string and char literals act correctly in both. Also in kitty if I copy any of these concealed chars, it copies the correct underlying char.

**Comment by phaazon** [comment]
I’ve seen this from time to time, and I think it might be a bug with the converter code `byte_pos -> (line, col)`. But I wrote that a while ago and it never failed, so I don’t think it’s a regression (it was probably a hidden bug somewhere).

I’m a bit surprised several people are hit by the bug _just now_ (me included!).

**Comment by phaazon** [comment]
So I reproduced at work but not entirely sure _how_. I’m looking for a reproducible example, if anyone has one.

**Comment by postsolar** [comment]
@phaazon 
> So I reproduced at work but not entirely sure how. I’m looking for a reproducible example, if anyone has one.

I just reproduced this with zero configuration for both Kakoune and KTS, on a new user on my system. Install PureScript grammar and create a file with `.purs` extension, and paste this code
```
type A ∷ Type → Type
type A a = a
```

**Comment by postsolar** [comment]
If I create a buffer with
```
foo ∷ Bar → Baz
```
then inspecting `%opt{kts_highlighter_ranges}` produces this:
```
          foo                space            ∷                     space
21 1.1,1.3|ts_variable 1.4,1.4|ts_unknown 1.7,1.8|ts_operator 1.8,1.8|ts_unknown
#                                            ↑
#                                    should be 1.5,1.5
```

Now, if I try to reproduce this error and create correct range manually, it works fine. If I then add an overlapping range it results in an escape sequence, but **only if the underlying char is a Unicode char** — e.g. ASCII, cyrillics, greek work fine. So from what I could guess there are two problems:
- KTS fails to produce correct range-specs.
- Kakoune fails to report incorrect range-specs (assuming visual breaks is not a report).

**Comment by phaazon** [comment]
Thank you! I’ll address the KTS problem. For Kakoune, it’s probably a bug, yes. We should probably open an issue upstream.

**Comment by phaazon** [comment]
@postsolar I just pushed the fix to the `fix/156` branch. May you try with it, please? :) There seems to be some super weird latency on GitHub, so don’t rush too much: there should be two commits on that branch; one adding the unit test, one fixing the code. If you only see one, then the fix is not there yet.

**Comment by postsolar** [comment]
Not there yet:
![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/de73619c-b89a-48af-a2dc-6b61662c05f0)

I got it wrong when I said above "should be 1.5,1.5" for that example. I figured out the starting position of the highlighting range should be the byte length of all the characters on the line before the range + 1, and its length should be the byte length of the characters in the range. So in example on this screenshot it would need to be `1.7,1.13` (save for a potential off by 1 error :) ), because there are 6 bytes before it and the highlighting range `ᾩᾩ` itself is also 6 bytes. That's how I fixed a similar issue in https://github.com/postsolar/jump.kak/issues/1

**Comment by phaazon** [comment]
> jump.kak

Damn, I was working on something like that in https://github.com/phaazon/hop.kak. Glad to see you have something already there!

---

For the rest of your comment, yes, it should be the length indeed, so that’s probably what’s wrong with my current code — I used to use `char::utf8_len`, but now I’m just adding `1`, which is likely wrong. I’ll fix that, thanks!

**Comment by phaazon** [comment]
If I put the unicode text in a comment (which is parsed as a single big token by the JS parser, I get the right result), so this is clearly a bug with the way each individual (unicode) token is handled.

<img width="1368" alt="Screenshot 2023-11-30 at 09 07 12" src="https://github.com/phaazon/kak-tree-sitter/assets/506592/e5c2b819-9c18-454c-98d9-54711e4b2d48">

**Comment by phaazon** [comment]
<img width="767" alt="Screenshot 2023-11-30 at 10 22 17" src="https://github.com/phaazon/kak-tree-sitter/assets/506592/de88c421-4a85-4e37-ab8c-fd0fa199c5ac">

May you try again @postsolar? Thanks!

**Comment by postsolar** [comment]
A lot better now! Minor nitpick though: notice how on line 78 the newline character `¬` assumes the color of the last character `→`, which doesn't happen elsewhere.
![image](https://github.com/phaazon/kak-tree-sitter/assets/120750161/667ca4c0-eeca-432f-822d-a1b505f311e3)

**Comment by phaazon** [comment]
Hm, indeed. Not completely fixed then. Thanks again, I’ll give it another look tonight.

**Comment by phaazon** [comment]
I do not reproduce that though. Which Kakoune version are you using? I’m on `Kakoune v2023.08.05-128-g4499b26c`.

**Comment by postsolar** [comment]
`Kakoune v2023.08.05-154-g9797c27e`. I have some patches applied in this version though, but none of them seem to relate to this topic.

Sorry, I should've posted a reproducible example earlier. With PureScript grammar:
```
a = b ×
  c
```

which gives me:
```
  1.1,1.1|ts_function
  1.2,1.2|ts_unknown
  1.3,1.3|ts_operator
  1.4,1.4|ts_unknown
  1.5,1.5|ts_variable
  1.6,1.6|ts_unknown
  1.7,1.9|ts_operator  <--- should be 1.7,1.8 ?
  1.9,2.2|ts_unknown
  2.3,2.3|ts_variable
  2.4,3.1|ts_unknown
```

the highlighter used is
```
addhl global/ show-whitespaces -only-trailing
```

**Comment by postsolar** [comment]
Same for JS:
```
a = ᾩ
  (b)

  1.1,1.1|ts_variable
  1.2,1.2|ts_unknown
  1.3,1.3|ts_operator
  1.4,1.4|ts_unknown
  1.5,1.8|ts_function
  1.8,2.2|ts_unknown
  2.3,2.3|ts_punctuation_bracket
  2.4,2.4|ts_variable
  2.5,2.5|ts_punctuation_bracket
  2.6,3.1|ts_unknown
```

**Comment by phaazon** [comment]
>   1.7,1.9|ts_operator  <--- should be 1.7,1.8 ?

`×` takes two bytes, so it’s fine. I don’t reproduce:
<img width="245" alt="Screenshot 2023-12-01 at 09 50 11" src="https://github.com/phaazon/kak-tree-sitter/assets/506592/2078a421-fd89-44ec-9ff8-ac88d455326d">

**Comment by phaazon** [comment]
The mapper is correct, it moves by the right amount of bytes. I think the problem is how the mapper is used (how the `start` / `end` range is computed).

**Comment by phaazon** [comment]
`mapper.advance(end - 1);`

That `-1` means « minus one character. » It should probably be « minus the byte length of the last character. »

**Comment by postsolar** [comment]
I have it showing up with Kakoune built from master and from 4499b26c (i.e. your version) 🤔.

**Comment by hadronized** [comment]
@postsolar do you still reproduce?

**Comment by postsolar** [comment]
@hadronized
I have since switched to NixOS and I've been unable to run KTS at all ever since. But I think the issue was resolved and that bit with the range of the last character on the line including the newline character itself deserves a separate issue, if somebody comes across it. But the topic of this issue has long been resolved :tada: :+1:

**Comment by Sivecano** [comment]
it seems to have been resolved (at least for me)

**Comment by hadronized** [comment]
Cool, thanks for the feedback. @postsolar what’s up with Nix issues though?
