### ISSUE TITLE
Figure out the UX for mappings

### ISSUE THREAD

**Issue by krobelus** [hadronized/kak-tree-sitter#234]
We currently run

```kakrc
define-command -hidden kak-tree-sitter-textobjects-enable %{
    map -docstring 'function (tree-sitter)'  buffer object f   '<a-;> kak-tree-sitter-req-textobjects function<ret>'
    map -docstring 'class (tree-sitter)'     buffer object t   '<a-;> kak-tree-sitter-req-textobjects class<ret>'
    map -docstring 'comment (tree-sitter)'   buffer object '#' '<a-;> kak-tree-sitter-req-textobjects comment<ret>'
    map -docstring 'parameter (tree-sitter)' buffer object 'v' '<a-;> kak-tree-sitter-req-textobjects parameter<ret>'
}
```

while [LSP recommends these](https://github.com/kakoune-lsp/kakoune-lsp#configure-mappings):

```kakrc
map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object e '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object k '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'
```

As far as I know, convention for Kakoune plugins is to provide commands and perhaps user-modes with mappings,
but not add mappings to existing Kakoune modes.
The only exception I can think of is the great [kakoune-text-objects](https://github.com/Delapouite/kakoune-text-objects) but that's kind of the point of that plugin.
LSP also adds some mappings but those are mostly historical.
LSP briefly added some [object mappings] but later [stopped].
The mappings were carefully chosen to not collide with kakoune-text-objects.

I'm absolutely happy to break this convention and have 3rd party plugins add mappings.
But if we do that, we should design them well and make sure that the plugins work together.
I think it would be a disservice to users if plugin load order mattered because they override each other's mappings. We can do better.
One issue with supplying default mappings is that it becomes painful to change them, hence the need for good design.

I'm tempted to change the LSP recommended bindings of `e`/`k` to `<a-f>`/`<a-t>`, which is easier to remember and matches with tree-sitter.
Of course us taking `f` and `t` means that kakoune-text-objects is left behind, unless we figure something out.. I'm sure can, if needed (cc @Delapouite).

> map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'

I wonder if tree sitter has an equivalent for this? As in, select any syntax node? Probably not very useful since tree-sitter gives many more tokens.

The goals of this issue are:
1. [ ] Figure out whether we should provide default mappings, or whether to add them to the README (or wiki I guess)
2. [ ] Whichever way we go, make sure the LSP and tree-sitter are consistent
3. [ ] For the mappings that both tree-sitter and LSP provide:
   1. [ ] since tree-sitter is more reliable for this (IME), make it take precedence automatically if both are installed
   2. [ ] perhaps we should even deprecate LSP here (if it provides no extra functionality)

I currently prefer simply making LSP match tree-sitter with `<a-f>` and such (because today's inconsistency is super confusing),
then there is also no overlap.

BTW Thanks for the object mode mappings; sorry for the long issue, I mainly don't want to let LSP bitrot here.

[object mappings]: https://github.com/kakoune-lsp/kakoune-lsp/commit/3d4d649 (Introduce object mode commands to select functions and other symbols, 2022-03-20)
[stopped]: https://github.com/kakoune-lsp/kakoune-lsp/commit/5bad166 (Add section with recommended mappings instead of mapping keys ourselves, 2022-08-07)

**Comment by krobelus** [comment]
sorry I  just realized that text object support hasn't been merged yet; I'm using @topisani's develop branch

**Comment by hadronized** [comment]
I have some local mappings, and clearly, I think that:

1. We could provide a function that creates a user-mode, and let the user decide how to enter that mode.
2. In all cases, we should document all the functions, commands and parameters on the wiki. I will do that once text-objects are stable enough.

I will not make any « default » mappings, even in user mode. The only thing I could accept is a default user-mode, and even then, it shouldn’t be sourced automatically (I’m calling that `tree-sitter`, but a user might want to have a mode named similarly without clashing with the one from KTS).

**Comment by hadronized** [comment]
I have set something up on `master` with `--with-text-objects`. So far it’s doing the job correctly.
