### ISSUE TITLE
Default config doesn't work

### ISSUE THREAD

**Issue by tom-huntington** [hadronized/kak-tree-sitter#294]
I installed with crates.io
```
~/.config/kak-tree-sitter
❯ ktsctl info
configuration error: cannot read configuration: No such file or directory (os error 2)

~/.config/kak-tree-sitter
❯ wget -q -O config.toml https://raw.githubusercontent.com/hadronized/kak-tree-sitter/master/default-config.t
oml

~/.config/kak-tree-sitter
❯ ktsctl info
configuration error: cannot parse configuration: TOML parse error at line 1, column 1
  |
1 | # kak-tree-sitter default configuration file.
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `url`

❯ ktsctl -fci rust
configuration error: cannot parse configuration: TOML parse error at line 1, column 1
  |
1 | # kak-tree-sitter default configuration file.
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
missing field `url`
```

**Comment by hadronized** [comment]
Hm, that’s probably due to the fact the configuration was changed lately due to new versions of kts and ktsctl. I would suggest to copy the `config.toml` file from the repository by checking it out to the tag of the version (`--version`).

**Comment by hadronized** [comment]
Alternatively, if you want to benefit from all the last good stuff, you can use the local repository. It ships with the default config (so you don’t even need a config file if you don’t intend changing the defaults). I plan on adding binary releases and make a full release ~soon.

**Comment by tom-huntington** [comment]
For executables, perhaps the best experience is something like
```
cargo install --git https://github.com/username/repository_name.git --branch main
```
