### ISSUE TITLE
Support local file paths for queries and grammars

### ISSUE THREAD

**Issue by sclu1034** [hadronized/kak-tree-sitter#34]
People usually have already figured out how to manage their collection of configuration files (i.e. their dotfiles) and move it between systems, and when customizing queries or grammars, adding another few files to that tends to be easier than to ensure that

- those customizations exist somewhere they can be cloned from
- when that somewhere is private, this tool's internal `git clone` call knows the credentials for that

Shenanigans with git being able to clone from a local path exist as a workaround, but create an unnecessary copy.

And side note: The doc comments in `kak-tree-sitter-config/src/lib.rs` explain how `LanguageQueriesConfig::url` can be omitted to re-use the one from the grammar. The wiki doesn't mention that.

**Comment by sclu1034** [comment]
> If you are using your own queries, you don’t need `ktsctl`

Where would I configure them, then? Apart from the config file in question, the wiki only really mentions queries in the context of them being downloaded from Helix.

> Or are you saying that you would like `ktsctl` to clone from a local path?

As I said, that is possible, but creates an unnecessary copy.

**Comment by phaazon** [comment]
> Where/how would I point the daemon to them, then? Apart from the config file in question, the wiki only really mentions queries in the context of them being downloaded from Helix.

Good point, I need to update the wiki. `kak-tree-sitter` reads from the config to get a listing of languages it needs to load, and then loads those from `$XDG_DATA_DIR/kak-tree-sitter/{grammar,queries}`.

I’ll add a section about that in the wiki.
